shared:
  box: oraclebase/oracle-7
  non_rotational: 'on'
  asm_disk_1: /u05/VirtualBox/shared/ol7_122_rac/asm_disk_1.vdi
  asm_disk_2: /u05/VirtualBox/shared/ol7_122_rac/asm_disk_2.vdi
  asm_disk_3: /u05/VirtualBox/shared/ol7_122_rac/asm_disk_3.vdi
  asm_disk_4: /u05/VirtualBox/shared/ol7_122_rac/asm_disk_4.vdi
  asm_disk_size: 20

dns:
  vm_name: ol7_122_dns
  mem_size: 1024
  cpus: 2
  public_ip: 192.168.56.100

node1:
  vm_name: ol7_122_rac1
  mem_size: 7168
  cpus: 2
  public_ip: 192.168.56.101
  private_ip: 192.168.1.101
  u01_disk: ./ol7_122_rac1_u01.vdi

node2:
  vm_name: ol7_122_rac2
  mem_size: 6144
  cpus: 2
  public_ip: 192.168.56.102
  private_ip: 192.168.1.102
  u01_disk: ./ol7_122_rac2_u01.vdi
